### ISSUE TITLE
[front] 当選者を手動追加

### ISSUE THREAD

**Issue by TsubasaOura** [NUTFes/lottery#166]
## 開発目的
http://localhost:8888/admin で確認できるToolbarから当選者を追加できるようにしてほしいです！

## 考えられる開発内容
`app/src/components/Toolbar`にあるフォームに

- 当選者の学籍番号

を入力したのち，設定ボタンを押すと
http://localhost:8000/api/winner
にフォームの内容がPOSTされ，設定できるようにしてほしい！！

できれば再読み込み無しで，Tableに追加されたらうれしいけど，コンポーネントが別のとこにあるから難しい？
ここら辺はちょっとわかってないです。

## 備考
以下からAPIのドキュメントの確認とAPIのテストができます。
http://localhost:8000/docs

**Comment by YushiroDodo63** [comment]
#174 で remake したためクローズします
